services:
  frontend:
    build: ./frontend
    ports:
      - 8080:8080
    depends_on:
      - backend
    environment:
      BACKEND_PORT: 9000
      BACKEND_DNS: backend
  backend:
    build: ./backend
    depends_on:
      - redis
    environment:
      REDIS_DNS: redis

  redis:
    image: redis:latest
    ports:
      - 6379:6379


volumes:
  redis-data:
