services:
  frontend:
    build: ./frontend
    ports:
      - 8080:8080
    depends_on:
      - backend
    environment:
      BACKEND_PORT: 9000
      BACKEND_DNS: backend
  backend:
    build: ./backend