version: "3.8"
services:
    backend:
        build:
            context: ./backend
            dockerfile: ./Dockerfile
        image: backend:latest
    
    frontend:
        build:
            context: ./frontend
            dockerfile: ./Dockerfile
        image: frontend:latest