apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortune-cookie
  labels:
    app: fortune-cookie
env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/backend

spec:
  replicas: 1
  selector:
    matchLabels:
      app: fortune-cookie
      tier: backend
      track: stable
  template:
    metadata:
      labels:
        app: fortune-cookie
        tier: backend
        track: stable
    spec:
      containers:
        - name: fortune-cookie
          image: "IMAGE_NAME"