apiVersion: v1
kind: Service
metadata:
  labels:
    app: fortune-cookie
  name: fortune-cookie-service
spec:
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 80
  selector:
    app: fortune-cookie
  type: NodePort