apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend
  name: service-backend
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 9000
  selector:
    app: backend
  type: ClusterIP