name: CI

on:
  push:
    branches: [ "Ci-jobs" ]
  pull_request:
    branches: [ "development" ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

  build_frontend:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build frontend 
      run: cd frontend && go build -v

    - name: Test frontend
      run: cd frontend && go test -v

  build_backend:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build backend
      run: cd backend && go build -v 

    - name: Test backend
      run: cd backend && go test -v  # I noticed you were testing frontend again. I assume this is a mistake and corrected it.

  docker_setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Build and start services
      run: docker-compose up --build -d

  test_app:
    needs: docker_setup
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Test application availability
      run: |
        sleep 15 
        curl http://localhost:8080
      continue-on-error: true

    - name: Set script permissions
      run: chmod +x scripts/test_endpoints.sh

    - name: Test application endpoints
      run: ./scripts/test_endpoints.sh

    - name: Tear down services
      run: docker-compose down