name: CI

on:
  push:
    branches: [ "redis-kubernetes" ]
  pull_request:
    branches: [ "development" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build frontend 
      run: cd frontend && go build -v

    - name: Test frontend
      run: cd frontend && go test -v 
      
    - name: Build backend
      run: cd backend && go build -v 

    - name: Test backend
      run: cd frontend && go test -v

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Build and start services
      run: docker-compose up --build -d

    - name: Test application availability
      run: |
        sleep 15 
        curl http://localhost:8080
      continue-on-error: true

    - name: Tear down services
      run: docker-compose down


