name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build frontend 
      run: cd frontend && go build -v
      
    - name: Build backend
      run: cd backend && go build -v 

    - name: frontend Test
      run: cd frontend && go test -v 

    - name: backend Test
      run: cd frontend && go test -v
