name: Run commands on different operating systems
on:
  push:
    branches: [ "04-cd" ]
  pull_request:
    branches: [ "development" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: get kubeconfig
      run: echo "${{ secrets.KUBECONFIG }}" | base64 -d > kubeconfig
      
    - name: deploy kubernetes
      run: kubectl --kubeconfig kubeconfig <your kubectl commands>