on:
  push:
    branches: [ "04-cd" ]
  pull_request:
    branches: [ "development" ]

env:
  BACKEND_IMAGE: gnavlos/backend:03-container-registry
  FRONTEND_IMAGE: gnavlos/frontend:03-container-registry

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Build and push backend image
      run: |
        docker buildx build --tag $BACKEND_IMAGE ./backend
        docker push $BACKEND_IMAGE

    - name: Build and push frontend image
      run: |
        docker buildx build --tag $FRONTEND_IMAGE ./frontend
        docker push $FRONTEND_IMAGE

    - name: Set up kubectl
      uses: azure/k8s-set-context@v1
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }}

    - name: Deploy to Kubernetes
      run: cd kubernetes && kubectl apply -f . 
