on:
  push:
    branches: [ "04-cd" ]
  pull_request:
    branches: [ "development" ]

env:
  BACKEND_IMAGE: gnavlos/backend:03-container-registry
  FRONTEND_IMAGE: gnavlos/frontend:03-container-registry

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-docker@v2

    - name: Build and push backend image
      run: |
        docker build -t $BACKEND_IMAGE ./backend
        docker push $BACKEND_IMAGE

    - name: Build and push frontend image
      run: |
        docker build -t $FRONTEND_IMAGE ./frontend
        docker push $FRONTEND_IMAGE

    - name: Deploy to Kubernetes
      uses: steebchen/kubectl@v2
      with:
        args: apply -f kubernetes/deployment-backend.yml -f kubernetes/service-backend.yml -f kubernetes/deployment-frontend.yml -f kubernetes/service-frontend.yml
