on:
  push:
    branches: [ "04-cd" ]
  pull_request:
    branches: [ "development" ]

env:
  BACKEND_IMAGE: gnavlos/backend:03-container-registry
  FRONTEND_IMAGE: gnavlos/frontend:03-container-registry

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up KUBECONFIG
      run: |
        echo "$KUBECONFIG" > kubeconfig.yaml

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f kubernetes/ --kubeconfig <(echo "$KUBECONFIG")
