name: Run commands on different operating systems
on:
  push:
    branches: [ "04-cd" ]
  pull_request:
    branches: [ "development" ]

env:
  BACKEND_IMAGE: gnavlos/backend:03-container-registry
  FRONTEND_IMAGE: gnavlos/frontend:03-container-registry

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - uses: actions/checkout@master
